### ISSUE TITLE
Add a form so the user can update their password

### ISSUE THREAD

**Issue by thorie7912** [thorie7912/savings#2]
* This should be on the Settings page https://savings.for-bitcoin.com/user/settings
* Should require submitting the old password once and the new password twice

**Comment by asad041** [comment]
Change password form added successfully. 

-  public->index.php [route (a)]
-  app->controller->Usercontroller [settingaction(u), changepasswordsubmit(a)]
-  app->model->auth [checkPasswordById(a)]
-  app->model->form->changePassword.php (a)
-  app->model->Users.php [saveuser(u)]
-  app->view->user->settings.phtml (u)
-  app->view->user->change-password.phtml (a)

[u: updated, a: added]

**Comment by thorie7912** [comment]
Done in PR #10
