### ISSUE TITLE
Should not accept 1.2345 as valid amount

### ISSUE THREAD

**Issue by thorie7912** [thorie7912/savings#65]
![image](https://user-images.githubusercontent.com/869094/31235786-3f044f92-a9a7-11e7-9bf1-4f5f3056fdd3.png)

We should allow the following:

`1` (saved in DB as `1.00`)
`1.5` (saved in DB as `1.50`)
`1.55` (saved in DB as `1.55`)
`1.555` (should be error, saying Amount must be in format #.##)

This should be applied to both Amount and (User)Max.

**Comment by asad041** [comment]
There's problem with **orders** table, columns **amount** and **maxAmount** are type `int` so I think we need to change that as well, to `float`

**Comment by thorie7912** [comment]
You should be able to add a new SQL script that will modify the `int` to `float`.

**Comment by asad041** [comment]
Already modified with `SQL` script
